### ISSUE TITLE
Sign-In doesn't work in the Client Example Application

### ISSUE THREAD

**Issue by st-keller** [adorsys/secure-token-service#10]
Starting the the example application (posters-version) locally seems to go quite smoothly.
Angular-App and Keycloak are accessible, but clicking on the "Sign in"-Button show an empty page.
Examining the network shows, that a request is sent to auth-endpoint of keycloak that get a 404-error:
`http://localhost:8080/auth/realms/moped/protocol/openid-connect/auth?client_id=moped-client&redirect_uri=http%3A%2F%2Flocalhost%3A8090%2F&state=2ab24cdf-50cf-44da-9c06-32955b8bccde&nonce=25a5c8b5-6f7a-4d51-91cf-7bd1393a1213&response_mode=fragment&response_type=id_token%20token&scope=openid%20sts-service-component`

Looks like as if realm "moped" doesn't exist:

`keycloak_1                 | 10:05:17,545 WARN  [org.keycloak.events] (default task-17) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=8eb52d4c-efaa-4806-bdfc-0b28bc7f3f40, ipAddress=172.20.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=http://localhost:8080/auth/admin/master/console/, code_id=626b7ae4-8207-47b9-a9de-6327b0ab02a7, username=admin`

```
keycloak_1                 | 10:07:46,285 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-28) RESTEASY002010: Failed to execute: javax.ws.rs.NotFoundException: Realm does not exist
keycloak_1                 | 	at org.keycloak.services.resources.RealmsResource.init(RealmsResource.java:202)
keycloak_1                 | 	at org.keycloak.services.resources.RealmsResource.getProtocol(RealmsResource.java:112)
keycloak_1                 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1                 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak_1                 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1                 | 	at java.lang.reflect.Method.invoke(Method.java:498)
keycloak_1                 | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.createResource(ResourceLocatorInvoker.java:79)
keycloak_1                 | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.createResource(ResourceLocatorInvoker.java:58)
keycloak_1                 | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
keycloak_1                 | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
keycloak_1                 | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
keycloak_1                 | 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
keycloak_1                 | 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
keycloak_1                 | 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
keycloak_1                 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
keycloak_1                 | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
keycloak_1                 | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
keycloak_1                 | 	at org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:90)
keycloak_1                 | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
keycloak_1                 | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
keycloak_1                 | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
keycloak_1                 | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
keycloak_1                 | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
keycloak_1                 | 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
keycloak_1                 | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1                 | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
keycloak_1                 | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
keycloak_1                 | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1                 | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
keycloak_1                 | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
keycloak_1                 | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
keycloak_1                 | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
keycloak_1                 | 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
keycloak_1                 | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
keycloak_1                 | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1                 | 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
keycloak_1                 | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1                 | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1                 | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
keycloak_1                 | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
keycloak_1                 | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
keycloak_1                 | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
keycloak_1                 | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
keycloak_1                 | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
keycloak_1                 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
keycloak_1                 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
keycloak_1                 | 	at java.lang.Thread.run(Thread.java:748)
keycloak_1                 | 

```

**Comment by borisskert** [comment]
Cant reproduce this error. If you still have issues, try deleting the temporary directory `.docker/` in your workspace and rerun your docker-compose command
